### ISSUE TITLE
Issue Label の文字色をコントラストによって変化させる

### ISSUE THREAD

**Issue by amotarao** [mikkame/lets-contribute#13]
**現在どのようなことが不便ですか？**

Issue Label の文字色が常時黒
<img width="215" alt="スクリーンショット 2020-05-25 19 11 19" src="https://user-images.githubusercontent.com/8909592/82803461-8a06dd00-9ebb-11ea-8880-5a677b2cf9be.png">

**それを解決するにはどうすれば良いと思いますか？**

GitHubのようにコントラストに応じて自動で色を出し分けしたい
<img width="180" alt="スクリーンショット 2020-05-25 19 11 02" src="https://user-images.githubusercontent.com/8909592/82803439-7f4c4800-9ebb-11ea-9792-80dafd5081c4.png">

**Comment by mikkame** [comment]
https://stackoverflow.com/questions/1855884/determine-font-color-based-on-background-color

この辺のアルゴリズムをお借りする感じで解決・・・でしょうか

**Comment by amotarao** [comment]
ですね...！

https://github.githubassets.com/assets/github-bootstrap-8adc1822.js
`return+((299*(t>>16&255)+587*(t>>8&255)+114*(255&t))/1e3/255).toFixed(2)} ` 

GitHub自体、YIQというもので判定してるようでした。
