### ISSUE TITLE
英語のサイトと解釈される

### ISSUE THREAD

**Issue by amotarao** [mikkame/lets-contribute#15]
**バグの詳細**
`<html lang=en>` のため英語のサイトと解釈されている

**再現手順**
1. ページを開く
2. 日本語なのに英語ページと判断され、翻訳するか聞かれる (Chrome)

**期待される挙動**
翻訳するか聞かれない

**スクリーンショット**
<img width="822" alt="スクリーンショット 2020-05-25 19 28 14" src="https://user-images.githubusercontent.com/8909592/82804799-e7039280-9ebd-11ea-8bb7-86f99692bccc.png">

<img width="134" alt="スクリーンショット 2020-05-25 19 28 08" src="https://user-images.githubusercontent.com/8909592/82804810-e9fe8300-9ebd-11ea-9a17-d2c83d15fba5.png">

**環境:**
 - OS: MacOS
 - Browser chrome
 - Version 83

**申し送り事項**
とくになし

**Comment by mikkame** [comment]
デフォのままですね・・・。
meta系は手付かずなのでデスクリプションいれてないかも
というかタイトルも。Vue meta 入れて対応ですかね。

**Comment by amotarao** [comment]
ページ1種しかない現状では、public/index.html を直接触ってしまってもいいと思いますー！

**Comment by mikkame** [comment]
たしかに。
index.htmlを修正する方向にします！
descriptionとかもついでに書くのでこっちで巻きます！
