### ISSUE TITLE
githubリボンがクリックできない（スマホ）

### ISSUE THREAD

**Issue by mikkame** [mikkame/lets-contribute#17]
**バグの詳細**
githubリボンが押せない
**再現手順**

スマホで右上のGitHubリボンが押せない

**期待される挙動**
押せるようになる

**スクリーンショット**
可能なら添付してください

**環境:**
 - スマホ

**申し送り事項**
描画順の問題。
多分芝風背景に当たり判定を吸われている

**Comment by daichi-iwamoto** [comment]
@mikkame 
`z-index:1`つけてあげるだけで解決できそうです！
