### ISSUE TITLE
単語の修正

### ISSUE THREAD

**Issue by asuchi0819** [mikkame/lets-contribute#23]
**バグの詳細**
HTMLやCSSなどの、プログラミング言語以外も含まれてるが、「プログラミング言語」とひとくくりにされている。

**スクリーンショット**
![image](https://user-images.githubusercontent.com/45027336/82836617-cd843a00-9f01-11ea-9f38-60fde3940d8f.png)

**Comment by asuchi0819** [comment]
PR出します。

**Comment by mikkame** [comment]
こちらはgithubの言語絞り機能（拡張子より使用言語を推定）のため一律言語表記となっています。
なお五十音順です。

明確には言語、フレームワーク、言語では無いものも含まれていますが伝わるので良いのではと思っております。

**Comment by asuchi0819** [comment]
了解しました。お手数をおかけしました。
