### ISSUE TITLE
文字が要素を飛び出してしまう。

### ISSUE THREAD

**Issue by kyoya0819** [mikkame/lets-contribute#24]
**バグの詳細**
連続した英字等の特定の条件がそろったときに、文字が飛び出してしまいます。
スマホでかなりの確率で見ることができます。

**再現手順**
スマホでアクセスする。
当方確認端末、iPhone7, SE1, WindowsPC

**スクリーンショット**
![image](https://user-images.githubusercontent.com/45027336/82836795-3d92c000-9f02-11ea-8d73-822682875486.png)

**Comment by asuchi0819** [comment]
[word-break](https://developer.mozilla.org/ja/docs/Web/CSS/word-break)の適切な指定で解消できそうです。

**Comment by rokumura7** [comment]
@mikkame さん
こちらのチケット対応したいと思います。

デベロッパーツールのiPhoneSEで検証したところ、
Issueコンポーネント内のリポジトリ名、タイトル、タグ、内容の表示崩れが確認できました。
![image](https://user-images.githubusercontent.com/54521076/107602511-26048e80-6c6d-11eb-94cb-3cfd304fe4fe.png)

@kyoya0819 さんの提案どおりword-breakを用いて改行を調整したいと思います。

**Comment by mikkame** [comment]
よろしくお願いします！

**Comment by kyoya0819** [comment]
~~このプロジェクト生きてたんだ~~

ご対応ありがとうございます！！

**Comment by rokumura7** [comment]
こういうサービス欲しかったと思っていたので盛り上げていきたいです😋

PR作りましたのでレビューお願いいたします🙇‍♂️
#41
