### ISSUE TITLE
完全に個人開発と思われるものの除外。

### ISSUE THREAD

**Issue by asuchi0819** [mikkame/lets-contribute#25]
**現在どのようなことが不便ですか？**
いくつかの、言語・FWで見てみたが、Fork 0, Star 0, Watch 1 のようなものが多かった。。

**それを解決するにはどうすれば良いと思いますか？**
コードを詳しく見てないのでわからないのですが、Fork数とStar数等で絞り込みを行ったほうが良いと思います。

**Comment by mikkame** [comment]
個人的には個人開発っぽいものにもPR送ってますし
それで何か繋がりができたりすると思いますので
オプションとして用意できればと思います

**Comment by reta-ygs** [comment]
言語によってコミュニティの規模が違うので、そう言った意味でも一律制限してしまうのはよろしくないように思います。
逆に、少人数開発に参加したい人もいるのであれば、絞り込み機能として実装するのはアリではないでしょうか。
