### ISSUE TITLE
1分あたり5回ロードするとバグる

### ISSUE THREAD

**Issue by mikkame** [mikkame/lets-contribute#4]
**バグの詳細**
1分あたり5回ロードするとバグる。
これはGithubAPIを非認証状態で行なっているからである。
また現在、１ロードごとに2クエリ消費している。

**再現手順**
ex) 
1. 1分以内に5回以上検索する

**期待される挙動**

- 検索クエリを減らす(or検索できる？)
- リミットになったらその旨アラートする
- リミットタイマー見たいの用意する？

**スクリーンショット**
可能なら添付してください

**環境:**

**申し送り事項**
申し送り事項がある場合はこちらに記載してください

**Comment by michi-h0623** [comment]
確かに再現しますね。
