### ISSUE TITLE
対応言語を増やして欲しい

### ISSUE THREAD

**Issue by rokumura7** [mikkame/lets-contribute#42]
**現在どのようなことが不便ですか？**
言語の選択肢を増やしたい。

どこまで対応するか難しいが、Scala, Kotlin, Dart, Clojureなど近年露出が増えている言語に対応したい。
[参考URL](https://madnight.github.io/githut/#/pull_requests/2020/4)

**それを解決するにはどうすれば良いと思いますか？**
https://github.com/mikkame/lets-contribute/blob/master/src/languages.ts に増やしたい言語を追加する。

**Comment by mikkame** [comment]
ありがとうございます。
これgithubのAPIできちんと検索できるようなら実装したいです！
検索出来るか確認お願いしてもよろしいでしょうか

**Comment by rokumura7** [comment]
> これgithubのAPIできちんと検索できるようなら実装したいです！
> 検索出来るか確認お願いしてもよろしいでしょうか
承知です！
