### ISSUE TITLE
さらに読み込むがさらに読み込めない

### ISSUE THREAD

**Issue by michi-h0623** [mikkame/lets-contribute#7]
**バグの詳細**
さらに読み込むボタンを押しても動かない

**再現手順**
1. ウェブサイト 'https://lets-contribute.netlify.app/' にアクセスする
2. プログラミング言語を選択する
3. 表示されたらもっと見るを押下する
4. 動かない

**期待される挙動**
もっと見るを押すと続きのページがロードされる。

**環境:**
 - MacOS Catalina 10.15.4
 - Google Chrome 81.0.4044.138 (Official Build) (64bit)

# 関連
#4

**Comment by mikkame** [comment]
APIの利用リミットになってるとこれが発生します。
